/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:4ce38f6a-de16-4eb3-9bca-011e07b3606a",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_isCQbn9Qg",
    "aws_user_pools_web_client_id": "26o73i5tousr1cqbfq32t6802t",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://z34iwz6sova3lnawniylwxcfnm.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-h62bg75vjjag7fgxbcnrl6lcau"
};


export default awsmobile;
